// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TableTennisHistoric.Datas;

#nullable disable

namespace TableTennisHistoric.Migrations
{
    [DbContext(typeof(TableTennisHistoricDbContext))]
    [Migration("20260327091217_UpdateMatchSet")]
    partial class UpdateMatchSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TableTennisHistoric.Models.Championship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Beginning")
                        .HasColumnType("date");

                    b.Property<int>("ChampionshipGroup")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Ending")
                        .HasColumnType("date");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Championship");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.ChampionshipFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Away")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Home")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Matchday")
                        .HasColumnType("int");

                    b.Property<int>("Nb_of_team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChampionshipFormat");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.ChampionshipMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Away_score")
                        .HasColumnType("int");

                    b.Property<int>("Away_teamId")
                        .HasColumnType("int");

                    b.Property<int>("ChampionshipId")
                        .HasColumnType("int");

                    b.Property<int?>("Home_score")
                        .HasColumnType("int");

                    b.Property<int>("Home_teamId")
                        .HasColumnType("int");

                    b.Property<int>("Matchday")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Away_teamId");

                    b.HasIndex("ChampionshipId");

                    b.HasIndex("Home_teamId");

                    b.ToTable("ChampionshipMatch");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.ChampionshipTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChampionshipId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId");

                    b.HasIndex("TeamId");

                    b.ToTable("ChampionshipTeam");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("License_number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name_abrev")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.CompetitionCoefficient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("SeasonId");

                    b.ToTable("CompetitionCoefficient");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.MatchSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Player1Score")
                        .HasColumnType("int");

                    b.Property<int>("Player2Score")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchSet");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Is_me")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("License_number")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.PlayerSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Points_middle")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Points_start")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.ToTable("PlayerSeason");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("End_date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Phase1_End_date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Start_date")
                        .HasColumnType("date");

                    b.Property<decimal?>("p1_drift")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("p2_drift")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.ToTable("Season");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.TableTennisMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("CompetitionCoefficientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date_match")
                        .HasColumnType("date");

                    b.Property<decimal>("My_points_at_match")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("OpponentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Opponent_points_at_match")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("StageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionCoefficientId");

                    b.HasIndex("OpponentId");

                    b.HasIndex("StageId");

                    b.ToTable("TableTennisMatch");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Championship", b =>
                {
                    b.HasOne("TableTennisHistoric.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.ChampionshipMatch", b =>
                {
                    b.HasOne("TableTennisHistoric.Models.Team", "Away_team")
                        .WithMany()
                        .HasForeignKey("Away_teamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTennisHistoric.Models.Championship", "Championship")
                        .WithMany()
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTennisHistoric.Models.Team", "Home_team")
                        .WithMany()
                        .HasForeignKey("Home_teamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Away_team");

                    b.Navigation("Championship");

                    b.Navigation("Home_team");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.ChampionshipTeam", b =>
                {
                    b.HasOne("TableTennisHistoric.Models.Championship", "Championship")
                        .WithMany("ChampionShipTeams")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTennisHistoric.Models.Team", "Team")
                        .WithMany("ChampionshipTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Championship");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.CompetitionCoefficient", b =>
                {
                    b.HasOne("TableTennisHistoric.Models.Competition", "Competition")
                        .WithMany("CompetitionCoefficients")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTennisHistoric.Models.Season", "Season")
                        .WithMany("CompetitionCoefficients")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.MatchSet", b =>
                {
                    b.HasOne("TableTennisHistoric.Models.TableTennisMatch", "Match")
                        .WithMany("Sets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.PlayerSeason", b =>
                {
                    b.HasOne("TableTennisHistoric.Models.Club", "Club")
                        .WithMany("PlayerSeasons")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTennisHistoric.Models.Player", "Player")
                        .WithMany("PlayerSeasons")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTennisHistoric.Models.Season", "Season")
                        .WithMany("SeasonPoints")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.TableTennisMatch", b =>
                {
                    b.HasOne("TableTennisHistoric.Models.CompetitionCoefficient", "CompetitionCoefficient")
                        .WithMany("TableTennisMatchs")
                        .HasForeignKey("CompetitionCoefficientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTennisHistoric.Models.Player", "Opponent")
                        .WithMany("TableTennisMatchs")
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTennisHistoric.Models.Stage", "Stage")
                        .WithMany("TableTennisMatchs")
                        .HasForeignKey("StageId");

                    b.Navigation("CompetitionCoefficient");

                    b.Navigation("Opponent");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Team", b =>
                {
                    b.HasOne("TableTennisHistoric.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Championship", b =>
                {
                    b.Navigation("ChampionShipTeams");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Club", b =>
                {
                    b.Navigation("PlayerSeasons");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Competition", b =>
                {
                    b.Navigation("CompetitionCoefficients");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.CompetitionCoefficient", b =>
                {
                    b.Navigation("TableTennisMatchs");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Player", b =>
                {
                    b.Navigation("PlayerSeasons");

                    b.Navigation("TableTennisMatchs");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Season", b =>
                {
                    b.Navigation("CompetitionCoefficients");

                    b.Navigation("SeasonPoints");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Stage", b =>
                {
                    b.Navigation("TableTennisMatchs");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.TableTennisMatch", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("TableTennisHistoric.Models.Team", b =>
                {
                    b.Navigation("ChampionshipTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
